### DISCUSSION TITLE
TrafficTarget without rule?

### DISCUSSION THREAD

**Discussion by SantoDE** [servicemeshinterface/smi-spec#188] [General]
Hey folks, 

we're currently wondering, if we didn't missinterpret the `TrafficTarget` rules for maesh.  What is supposed to happen, when the `TrafficTarget` has empty / non rules? Will it go with all traffic should be denied then? Or is it an allow for everything? It's probably the first, but just to be sure ;-)

**Comment by patricekrakow** [comment]
I am not using Maesh, but OSM. After "onboarding" the services in the Mesh (i.e. inject the container proxy in all pods) all traffic is blocked/denied (returning 404). Then, you MUST configure appropriate `TrafficTarget` to have traffic.

**Reply by SantoDE** [reply]
Yeah, that is fine. Not asking that. I asked especially for a `TrafficTarget` without `rules` :)

**Reply by patricekrakow** [reply]
OK, that's indeed an interesting question... will you just get a L4 access control?
When playing with OSM, I have tested this

```yaml
# traffic.L4.yaml
---
# Deploy the 'tcp-route' TCPRoute
apiVersion: specs.smi-spec.io/v1alpha3
kind: TCPRoute
metadata:
  name: tcp-route
  namespace: demo-01
spec: {}
---
# Deploy the 'allow-client-x-to-service-a' TrafficTarget
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha2
metadata:
  name: allow-client-x-to-service-a
  namespace: demo-01
spec:
  destination:
    kind: ServiceAccount
    name: service-a
    namespace: demo-01
    port: 3000
  rules:
  - kind: TCPRoute
    name: tcp-route
  sources:
  - kind: ServiceAccount
    name: client-x
    namespace: demo-01
```

in which the presence of the `rules` is pretty useless indeed.

If I (finally) understand your question right, you are asking if I could have written it just as:

```yaml
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha2
metadata:
  name: allow-client-x-to-service-a
  namespace: demo-01
spec:
  destination:
    kind: ServiceAccount
    name: service-a
    namespace: demo-01
    port: 3000
  sources:
  - kind: ServiceAccount
    name: client-x
    namespace: demo-01
```

Is this a good way to re-formulate your question ? Or, am I again next to your question ?
