### ISSUE TITLE
Clarification on TrafficSplit port mapping

### ISSUE THREAD

**Issue by jspdown** [servicemeshinterface/smi-spec#146]
Hi everyone,

While working on an implementation of this specification I discussed with colleagues about the Ports section of the [TrafficSplit](https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-split.md#ports) document. We got two different interpretation of the following sentences:

> There must be a match between a port on the root service and a port on every destination backend service. If they do not match, the backend service is not included and will not receive traffic.
> Mapping between port and targetPort occurs on each backend service individually. This allows for new versions of applications to change the ports they listen on and matches the existing implementation of Services.

In the following example:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 9000
      name: svc-a
      targetPort: 8080
  selector:
    app: svc-a

---
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: svc-b-8080
      targetPort: 80
    - port: 9000
      name: svc-b-9000
      targetPort: 81
  selector:
    app: svc-b

---
apiVersion: v1
kind: Service
metadata:
  name: svc-c
  namespace: test
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: svc-c-8080
      targetPort: 80
    - port: 9000
      name: svc-c-9000
      targetPort: 80
  selector:
    app: svc-c

---
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: server-split
  namespace: test
spec:
  service: svc-a
  backends:
    - service: svc-b
      weight: 80
    - service: svc-c
      weight: 20

```

Do we expect the traffic to goes on `svc-b-9000` and `svc-c-9000` or on `svc-b-8080` and `svc-c-8080`?
Do we expect the root service port mappings to be used?
