### ISSUE TITLE
[Proposal] Add a specification for UDP traffic

### ISSUE THREAD

**Issue by SantoDE** [servicemeshinterface/smi-spec#150]
**Describe the proposal**
For now, there is no specification for UDP traffic. A simple spec could look like that (similiar to the TCPRoute)

Example:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: udproutes.specs.smi-spec.io
spec:  
  group: specs.smi-spec.io
  scope: Namespaced 
  names:    
    kind: UDPRoute
    shortNames: 
      - ur
    plural: udproutes
    singular: udproute
  version: v1alpha3
  versions:
    - name: v1alpha3
      served: true
      storage: true
    - name: v1alpha3
      served: false
      storage: false
```

**Scope**
- [X] New specification
- [ ] Traffic Access Control
- [X] Traffic Specs
- [ ] Traffic Metrics
- [ ] Traffic Split

**Possible use cases**
Currently, to manage access control you can utilize `HTTPRouteGroup` and `TCPRoute` in conjunction with Traffic Targets. However, there is no way to manage access control for (raw) UDP traffic as of now. Therefore, a simple resource could already solve that case. Maesh could provide a first implementation, as it become a requirement for us.

I'm happy to discuss that e.g. at the next community meeting :)

Linked to: #108
