### ISSUE TITLE
TrafficSplit OpenAPI Validation is incorrect

### ISSUE THREAD

**Issue by jessesuen** [servicemeshinterface/smi-spec#154]
**Describe the proposal**

The OpenAPI validation for the TrafficSplit CRD definition has `service` and `backends` as required fields at the root level (https://github.com/servicemeshinterface/smi-sdk-go/blob/master/crds/split.yaml#L33-L36):

```yaml
  validation:
    openAPIV3Schema:
      required:
        - service
        - backends
```

But this should really be nested under a `spec` field, according to https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-split.md#specification

**Scope**
- [ ] New specification
- [ ] Traffic Access Control
- [ ] Traffic Specs
- [ ] Traffic Metrics
- [x] Traffic Split

**Possible use cases**
