### ISSUE TITLE
Add the possibility to constraint TrafficSplit based on sources, while aligning TrafficSplit with TrafficTarget

### ISSUE THREAD

**Issue by patricekrakow** [servicemeshinterface/smi-spec#190]
**Describe the proposal**
The current `TrafficSplit` allows to restrict routing based on (1) the HTTP request content via the `HTTPRouteGroup` and (2) the destination via (Kubernetes) services. But, it does not include (yet?) a possible restriction based on (3) the source, for which we could also use (Kubernetes) services.
I also think that we should align more the `TrafficSplit` structure with the `TrafficTarget` structure.

**Scope**
- [ ] New specification
- [x] Traffic Access Control
- [x] Traffic Specs
- [x] Traffic Metrics
- [x] Traffic Split

**Possible use cases**
The new structure of the `TrafficSplit` would look like the following

```yaml
kind: TrafficSplit
metadata:
  name: routing
  namespace: demo
spec:
  sources:
  - apiVersion: ... 
    kind: Service
    name: client-x-v1-0-0
  rules:
  - kind: HTTPRouteGroup
    name: alpha-api-routes
    matches:
    - get-path-01
  destination:
    kind: Service
    name: acme-api
    backends:
    - kind: Service
      name: service-a-v1-0-0
      weight: 90
    - kind: Service
      name: service-a-v1-1-0
      weight: 10
```

If this **draft** proposal would make sense to some of you, I can support it by a PR. Just let me know...

**Comment by patricekrakow** [comment]
The main purpose of this issue was to discuss the possibility to add a reference  to a _source_ `Service` within the `TrafficSplit`.

However looking at the current version of `TrafficTarget`, `TrafficSplit` and `TrafficMetrics`, it looks that they all use a **different way** to reference to other _resources_. So before modifying the `TrafficSplit` to add a reference  to a _source_ `Service`, I would first align the way to reference to other _resources_ for all SMI _resources_.

## Short Analysis

### `TrafficTarget`

The `TrafficTarget` resource is using the combination of `kind`, `name` and `namespace` to refer to other _resources_.

```yaml
spec:
  destination:
    kind: ServiceAccount
    name: service-a
    namespace: default
    port: 8080
  rules:
  - kind: HTTPRouteGroup
    name: the-routes
    matches:
    - metrics
  sources:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
```

> It looks like `rules[].namespace` is missing (?)

### `TrafficSplit`

The `TrafficTarget` resource is using `service` to refer to other _Services_  only.

```yaml
spec:
  service: website
  backends:
  - service: website-v1
    weight: 90
  - service: website-v2
    weight: 10
```

> It looks like `namespace` is missing (?)

### `TrafficMetrics`

The `TrafficMetrics` resource is also using (like `TrafficTarget`) the combination of `kind`, `name` and `namespace` to refer to other _resources_, but as children of a generic `resource` field.

```yaml
resource:
  name: foo-775b9cbd88-ntxsl
  namespace: foobar
  kind: Pod
```

> The `TrafficMetrics` resource does not have a `spec`field (?)

### `Canary` from [Flagger](https://github.com/weaveworks/flagger)

In addition to that, it seems that other CRD from other project, such as the `Canary` from the [Flagger](https://github.com/weaveworks/flagger) are using yet other structure to refer to other _resources_, such as `apiVersion`, `name` and `kind`:

```yaml
spec:
  # service mesh provider (optional)
  # can be: kubernetes, istio, linkerd, appmesh, nginx, skipper, contour, gloo, supergloo
  provider: istio
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
```

> It looks like `namespace` is missing (?)

## Preliminary Result

I found all these different ways to to refer to other _resources_ quite confusing, and I think we should select one way to be applied to all SMI _resources_.

Personally, I like

```yaml
<purpose>Ref:
  kind: ...
  name: ...
  namespace: ...
...
<purpose>Ref:
  - kind: ...
    name: ...
    namespace: ...
```
