### ISSUE TITLE
Add the (required) `apiVersion` field to all YAML file examples

### ISSUE THREAD

**Issue by patricekrakow** [servicemeshinterface/smi-spec#225]
**Describe the proposal**

I have noticed that all examples of YAML files do not include the (required) field `apiVersion`. For instance in [traffic-specs.md](https://github.com/servicemeshinterface/smi-spec/blob/afffa146eafbbc8eab8d7185fad959362d81726e/apis/traffic-specs/v1alpha4/traffic-specs.md) you have:

```yaml
kind: HTTPRouteGroup
metadata:
  name: the-routes
spec:
  matches:
  - name: metrics
    pathRegex: "/metrics"
    methods:
    - GET
  - name: health
    pathRegex: "/ping"
    methods: ["*"]
```

while I would expect

```yaml
apiVersion: specs.smi-spec.io/v1alpha4
kind: HTTPRouteGroup
metadata:
  name: the-routes
spec:
  matches:
  - name: metrics
    pathRegex: "/metrics"
    methods:
    - GET
  - name: health
    pathRegex: "/ping"
    methods: ["*"]
```

If there is no particular reason for omitting the  `apiVersion` field from the YAML file examples, I can prepare a PR to update the four specification files.

**Scope**
- [ ] New specification
- [X] Traffic Access Control
- [X] Traffic Specs
- [X] Traffic Metrics
- [X] Traffic Split

**Possible use cases**

N/A
