### ISSUE TITLE
The Header Match format in HTTPRouteGroup description is not consistent with smi-sdk-go

### ISSUE THREAD

**Issue by tokers** [servicemeshinterface/smi-spec#233]
Hi, them!

The description of the Header Match format for `HTTPRouteGroup` is:

```yaml
kind: HTTPRouteGroup
metadata:
  name: the-routes
  namespace: default
spec:
  matches:
  - name: android-insiders
    headers:
    - user-agent: ".*Android.*"
    - cookie: "^(.*?;)?(type=insider)(;.*)?$"
```

Here we can know the `headers` is an array, however the definition in smi-sdk-go is `map[string]string (https://github.com/servicemeshinterface/smi-sdk-go/blob/main/pkg/apis/specs/v1alpha4/http_route.go#L47).

So which one is correct?
