### ISSUE TITLE
Question about A/B testing with traffic splits

### ISSUE THREAD

**Issue by kate-osborn** [servicemeshinterface/smi-spec#243]
The A/B testing example in the spec contains the following configuration: 
```
kind: TrafficSplit
metadata:
  name: ab-test
spec:
  service: website
  matches:
  - kind: HTTPRouteGroup
    name: ab-test
  backends:
  - service: website-v1
    weight: 0
  - service: website-v2
    weight: 100
---
kind: HTTPRouteGroup
metadata:
  name: ab-test
matches:
- name: firefox-users
  headers:
  - user-agent: ".*Firefox.*"
```

According to the spec, all FireFox users will be routed to `website-v2` while all other users will be routed to the root Kuberentes service. 

Is there a way to configure all non FireFox users to be routed to `website-v1` instead of the root Kubernetes service?
