### ISSUE TITLE
Depreciation of TrafficRoutes in favor of supporting Kubernetes Gateway API - WIP

### ISSUE THREAD

**Issue by nicholasjackson** [servicemeshinterface/smi-spec#249]
This issue is to discuss the overlaps between SMI and Kubernetes Gateway API and the possibility that where there is an overlap SMI adopts Gateway API in replacement for its own resources concentrating purely on service mesh specific resources.

Gateway API Spec:
https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io

## TrafficSpecs Comparison

The below example shows comparable functionality as could be implemented using SMI or Gateway spec, the core difference in this specification is that SMI TrafficTarget controls service to service authorization. 

```yaml
kind: HTTPRouteGroup
metadata:
  name: the-routes
spec:
  matches:
  - name: metrics
    pathRegex: "/metrics"
    methods:
    - GET
  - name: health
    pathRegex: "/ping"
    methods: ["*"]

---
kind: TrafficTarget
metadata:
  name: path-specific
  namespace: default
spec:
  destination:
    kind: ServiceIdentity
    name: my-api
    namespace: default
  rules:
  - kind: HTTPRouteGroup
    name: the-routes
    matches:
    - metrics
  sources:
  - kind: ServiceIdentity
    name: my-service
    namespace: gateway-api-example-ns1
```

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: my-route
  namespace: gateway-api-example-ns2
spec:
  parentRefs:
  - kind: ServiceIdentity
    name: my-service
    namespace: gateway-api-example-ns1
  rules:
  - backendRefs:
    - name: my-api
      port: 8080
  matches:
    - path:
        value: "/metrics"
      method: GET
    - path:
        value: "/ping"
```

## Notes:
- Investigate if parentRefs could relate to proposed ServiceIdentity, Gateway spec seems loose enough
- How would service to service authorization be implemented with Gateway spec
- In the instance that Gateway spec is used to control a Kubernetes ingress controller, how do you determine if HTTPRoute should configure a gateway or east west service mesh traffic
-

**Comment by mikemorris** [comment]
For proposed switch to `HTTPRoute`, it was discussed in last community meeting how the owner of a service should be configuring an `HTTPRoute` to allow incoming connections - we should clarify how the `parentRefs` and `backendRefs` fields would be used, as this is a bit of the inverse of how `HTTPRoute` is used in the Gateway API, where routes bind to a `Gateway` with a `parentRef`, and require a [`ReferencePolicy`](https://gateway-api.sigs.k8s.io/v1alpha2/api-types/referencepolicy/) for a `backendRef` to direct traffic to a service in a different namespace.

Multiple `backendRefs` can be defined on an [`HTTPRouteRule`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteRule), and each [`backendRef`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.BackendRef) includes a weight which could be used for balancing traffic e.g. between v1 and v2 k8s services of a single logical service (this could point to separate `IdentityBinding` objects if we don't want to introduce weighting within the `IdentityBinding`?)

An HTTPRoute can also define multiple [`parentRefs`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.CommonRouteSpec), which I think would offer sufficient granularity to be used to allow traffic from, e.g. `{ kind: IdentityBinding, name: fooBinding, namespace: api }` or simply from a specific namespace. 

We've focused mostly on `HTTPRoute` for directing L7 traffic, would we also want [TCPRoute](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.TCPRoute) for L4 traffic, or just use the default behavior of and `HTTPRoute` routing all traffic when the scope is not narrowed with an [`HTTPRouteMatch`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteMatch)?

**Comment by keithmattix** [comment]
I have some questions about how we need to handle `hostname` for E/W traffic; I'm not sure that field makes total sense in a mesh context.

Additionally, I'm currently of the opinion that `parentRef` should only be a reference to the mesh and that identity shouldn't come into play here. In other words, I think traffic routing (`HTT and traffic policy (`TrafficTarget`) should stay separate

**Comment by howardjohn** [comment]
> I have some questions about how we need to handle hostname for E/W traffic; I'm not sure that field makes total sense in a mesh context.

Drive by comment from an Istio developer (speaking without consensus from Istio community) - IMO it should work like this:

A Route is bound to a _Service_ (TODO how exactly this fits in the API). What this means is "All requests to this Service should use this route". This should be identified by the Service **IP**.

Once we have a route selected, we follow the standard route matching. For HTTP `hostname`, that means we can match additional `Host` headers. For example,

```yaml
kind: HTTPRoute
parentRef:
- Service foo # TODO on syntax
hostname: [bar.com]
...
```

This would mean `curl foo` would get a 404, and `curl foo -H "Host: bar.com"` would match.

Similar applies to SNI for TLSRoute.

Note that this means that using Hostname with mesh would likely be pretty rare. It could maybe be useful for a service like, say, nginx that is doing its own vhost routing so you would call it with different Host headers, but definitely an exception.

This is _not_ what Istio is doing here, but I want to change it. Today Istio doesn't do any IP matching at all for HTTP, so everything is host header based. This has caused various issues described in https://docs.google.com/document/d/1NAccj8WyjBXOUsMdOHW9sWW6PeCnrIWpc3muBHd4Cs8/.
