### ISSUE TITLE
Virtual Service/Router/Balancer type concept

### ISSUE THREAD

**Issue by ibuildthecloud** [servicemeshinterface/smi-spec#37]
I don't see any type of ability to create a virtual service/router/balancer.  Something that physically doesn't exist but has routing rules to get to something that does.  Basically this ends up being something that looks a lot like Ingress.  You might say then use ingress but the service mesh basically has to subsume ingress functionality.  The reason being that ingress is north-south only but users need the same functionality east west and logically the same ACL, routing, metrics rules of north south should apply to east west.

So what I'd like to see is I create a service `foo` in k8s that has no selector.  Then create a resources like

```yaml
kind: Router
spec:
  service: foo
  routes:
  - match:
    # something referring to httpRouteGroup
    dest:
    # something to target a service (that can have traffic splitting applied)
```
