### ISSUE TITLE
Clarify traffic-split weighting semantics

### ISSUE THREAD

**Issue by olix0r** [servicemeshinterface/smi-spec#39]
Consider the following:
- We have a `blue` and `green` service and deployment.
- The `blue` deployment has 1 replica.
- The `green` deployment has 9 replicas.
- There is a service, `target`, with a traffic split:
```yaml
--
apiVersion: smi-spec.io/v1beta1
kind: TrafficSplit
metadata:
  name: target-split
spec:
  service: target
  backends:
  - service: blue
    weight: 1000m
  - service: green
    weight: 1000m
```

The behavior can either be:
1. 10% of the traffic is sent to each pod; OR
2. 50% of the traffic is sent to the blue pod and 5.5% of the traffic sent to each green pod.

I believe that the spec intends the latter, but as far as i can tell, the handling of weights is not described explicitly.
