### ISSUE TITLE
TrafficTarget: Allow traffic from everyone

### ISSUE THREAD

**Issue by surajssd** [servicemeshinterface/smi-spec#51]
Right now a typical `TrafficTarget` example looks like following:

```yaml
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: api-service-api
  namespace: default
destination:
  kind: ServiceAccount
  name: api-service
  namespace: default
  port: 8080
specs:
- kind: HTTPRouteGroup
  name: api-service-routes
  matches:
  - api
sources:
- kind: ServiceAccount
  name: website-service
  namespace: default
- kind: ServiceAccount
  name: payments-service
  namespace: default
```

src: https://github.com/deislabs/smi-spec/blob/master/traffic-access-control.md

So above says that allow traffic from pods with `ServiceAccount` `website-service` & `payments-service` to destination pods with `ServiceAccount` `api-service`. How do I allow traffic from everyone to the pods with `ServiceAccount` `api-service`? Is there a way to mention wildcard entry to allow traffic from anyone and everyone and not worry about who is sending the traffic in the `sources` section?
