### ISSUE TITLE
trafficsplit: Behavior with conflicting TrafficSplit instances

### ISSUE THREAD

**Issue by olix0r** [servicemeshinterface/smi-spec#59]
What is the expected behavior when multiple traffic split resources refer to the same apex service?

For example, given an _apex_ service:
```yaml
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: blue-green
spec:
  service: apex
  backends:
  - service: blue
    weight: 10m
  - service: green
    weight: 90m

---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: red-yellow
spec:
  service: apex
  backends:
  - service: red
    weight: 10m
  - service: yellow
    weight: 90m
```

An implementation could choose to merge these traffic splits so it becomes effectively:
```yaml
spec:
  service: apex
  backends:
  - service: blue
    weight: 10m
  - service: green
    weight: 90m
  - service: red
    weight: 10m
  - service: yellow
    weight: 90m
```

Or, we could dictate that this is illegal and require a validating admission controller to enforce service uniqueness.

Or, we could modify the spec to require that the TS resource name must match the apex service name...

This behavior should not remain undefined, however.
